name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: The commit SHA to test.
        required: true

concurrency:
  group: test-${{ inputs.commit_sha }}
  cancel-in-progress: true

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check
        run: |
          set -euo pipefail

          if [[ "$(( $RANDOM % 2 ))" != "1" ]]; then
            echo "No changes to test."
            exit 1
          fi
